using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MSOSync.Persistence;

namespace MSOSync.MetadataTests;

internal sealed class TestAppDbContext : AppDbContext
{
    public TestAppDbContext(DbContextOptions<AppDbContext> options) : base(options) { }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);
        // SQLite doesn't support SQL Server-specific column types like nvarchar(max) or datetime2(7).
        // Clear explicit column types so EF uses SQLite's default affinity rules.
        // Also, SQLite has no rowversion/timestamp type, so mark those as optional with no value generation.
        foreach (var entity in modelBuilder.Model.GetEntityTypes())
        {
            foreach (var prop in entity.GetProperties())
            {
                prop.SetColumnType(null);
                // Rowversion (timestamp) properties are auto-generated by SQL Server but not by SQLite.
                // Remove the rowversion behavior so SQLite treats them as nullable byte arrays.
                if (prop.ClrType == typeof(byte[]) && prop.IsConcurrencyToken)
                {
                    prop.ValueGenerated = Microsoft.EntityFrameworkCore.Metadata.ValueGenerated.Never;
                    prop.IsNullable = true;
                }
                // SQLite cannot order/compare DateTimeOffset in SQL. Store as a 64-bit
                // integer (ticks-encoded, order-preserving for UTC values) so predicates
                // like `t.ExpiresAt > now` translate.
                if (prop.ClrType == typeof(DateTimeOffset) || prop.ClrType == typeof(DateTimeOffset?))
                {
                    prop.SetValueConverter(new DateTimeOffsetToBinaryConverter());
                }
            }
        }
    }
}

internal static class TestDbContext
{
    public static AppDbContext Create()
    {
        var options = new DbContextOptionsBuilder<AppDbContext>()
            .UseSqlite("DataSource=:memory:")
            .Options;
        var db = new TestAppDbContext(options);
        db.Database.OpenConnection();
        db.Database.EnsureCreated();
        return db;
    }
}
