<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>NodeMetadata, TriggerMetadata, RouterMetadata, ChannelMetadata, ParameterMetadata</Description>
  </PropertyGroup>
  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
      <_Parameter1>MSOSync.MetadataTests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="MediatR" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" />
    <PackageReference Include="Microsoft.Extensions.Http" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\MSOSync.Common\MSOSync.Common.csproj" />
    <ProjectReference Include="..\MSOSync.Persistence\MSOSync.Persistence.csproj" />
    <ProjectReference Include="..\MSOSync.Plugin\MSOSync.Plugin.csproj" />
    <ProjectReference Include="..\MSOSync.Security\MSOSync.Security.csproj" />
  </ItemGroup>
</Project>
