// <auto-generated />
using System;
using MSOSync.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MSOSync.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MSOSync.Persistence.Entities.SyncAudit", b =>
                {
                    b.Property<long>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("audit_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AuditId"));

                    b.Property<string>("ActionName")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("action_name");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("create_time");

                    b.Property<string>("ObjectName")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("object_name");

                    b.Property<string>("Username")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("username");

                    b.HasKey("AuditId");

                    b.HasIndex("CreateTime")
                        .HasDatabaseName("IX_sync_audit_create_time");

                    b.HasIndex("Username")
                        .HasDatabaseName("IX_sync_audit_username");

                    b.ToTable("sync_audit", "msosync");
                });

            modelBuilder.Entity("MSOSync.Persistence.Entities.SyncBatchError", b =>
                {
                    b.Property<long>("ErrorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("error_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ErrorId"));

                    b.Property<long>("BatchId")
                        .HasColumnType("bigint")
                        .HasColumnName("batch_id");

                    b.Property<string>("ConflictType")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("conflict_type");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("error_message");

                    b.Property<long?>("EventId")
                        .HasColumnType("bigint")
                        .HasColumnName("event_id");

                    b.Property<DateTime?>("LastRetryTime")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("last_retry_time");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("retry_count");

                    b.HasKey("ErrorId");

                    b.HasIndex("BatchId")
                        .HasDatabaseName("IX_sync_batch_error_batch_id");

                    b.ToTable("sync_batch_error", "msosync");
                });

            modelBuilder.Entity("MSOSync.Persistence.Entities.SyncChannel", b =>
                {
                    b.Property<string>("ChannelId")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("channel_id");

                    b.Property<int>("BatchSize")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1000)
                        .HasColumnName("batch_size");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("enabled");

                    b.Property<int>("MaxBatchToSend")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(10)
                        .HasColumnName("max_batch_to_send");

                    b.Property<long>("MaxDataSize")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1048576L)
                        .HasColumnName("max_data_size");

                    b.Property<int>("Priority")
                        .HasColumnType("int")
                        .HasColumnName("priority");

                    b.HasKey("ChannelId");

                    b.ToTable("sync_channel", "msosync");
                });

            modelBuilder.Entity("MSOSync.Persistence.Entities.SyncDataEvent", b =>
                {
                    b.Property<long>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("event_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("EventId"));

                    b.Property<string>("ChannelId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("channel_id");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("create_time");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasColumnName("event_type");

                    b.Property<bool>("IsProcessed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_processed");

                    b.Property<string>("PkData")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("pk_data");

                    b.Property<string>("RowData")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("row_data");

                    b.Property<string>("SourceNodeId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("source_node_id");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("table_name");

                    b.Property<long?>("TransactionId")
                        .HasColumnType("bigint")
                        .HasColumnName("transaction_id");

                    b.Property<string>("TriggerId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("trigger_id");

                    b.HasKey("EventId");

                    b.HasIndex("CreateTime")
                        .HasDatabaseName("IX_sync_data_event_create_time");

                    b.HasIndex("TransactionId")
                        .HasDatabaseName("IX_sync_data_event_transaction_id");

                    b.HasIndex("ChannelId", "IsProcessed")
                        .HasDatabaseName("IX_sync_data_event_channel_processed");

                    b.ToTable("sync_data_event", "msosync");
                });

            modelBuilder.Entity("MSOSync.Persistence.Entities.SyncDataEventBatch", b =>
                {
                    b.Property<long>("EventId")
                        .HasColumnType("bigint")
                        .HasColumnName("event_id");

                    b.Property<long>("BatchId")
                        .HasColumnType("bigint")
                        .HasColumnName("batch_id");

                    b.HasKey("EventId", "BatchId");

                    b.ToTable("sync_data_event_batch", "msosync");
                });

            modelBuilder.Entity("MSOSync.Persistence.Entities.SyncIncomingBatch", b =>
                {
                    b.Property<long>("BatchId")
                        .HasColumnType("bigint")
                        .HasColumnName("batch_id");

                    b.Property<DateTime?>("AppliedTime")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("applied_time");

                    b.Property<long?>("ApplyTimeMs")
                        .HasColumnType("bigint")
                        .HasColumnName("apply_time_ms");

                    b.Property<string>("ChannelId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("channel_id");

                    b.Property<DateTime?>("ExtractTime")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("extract_time");

                    b.Property<DateTime?>("LoadTime")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("load_time");

                    b.Property<string>("NodeId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("node_id");

                    b.Property<int?>("RowCount")
                        .HasColumnType("int")
                        .HasColumnName("row_count");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint")
                        .HasColumnName("status");

                    b.HasKey("BatchId");

                    b.HasIndex("NodeId", "Status")
                        .HasDatabaseName("IX_sync_incoming_batch_node_status");

                    b.ToTable("sync_incoming_batch", "msosync");
                });

            modelBuilder.Entity("MSOSync.Persistence.Entities.SyncLock", b =>
                {
                    b.Property<string>("LockName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("lock_name");

                    b.Property<string>("LockOwner")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("lock_owner");

                    b.Property<DateTime?>("LockTime")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("lock_time");

                    b.HasKey("LockName");

                    b.ToTable("sync_lock", "msosync");
                });

            modelBuilder.Entity("MSOSync.Persistence.Entities.SyncMonitor", b =>
                {
                    b.Property<long>("SnapshotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("snapshot_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SnapshotId"));

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("create_time");

                    b.Property<string>("MetricName")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("metric_name");

                    b.Property<string>("MetricValue")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("metric_value");

                    b.Property<string>("NodeId")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("node_id");

                    b.HasKey("SnapshotId");

                    b.HasIndex("NodeId", "CreateTime")
                        .HasDatabaseName("IX_sync_monitor_node_create_time");

                    b.ToTable("sync_monitor", "msosync");
                });

            modelBuilder.Entity("MSOSync.Persistence.Entities.SyncNode", b =>
                {
                    b.Property<string>("NodeId")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("node_id");

                    b.Property<string>("GroupId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("group_id");

                    b.Property<int>("HeartbeatInterval")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(60)
                        .HasColumnName("heartbeat_interval");

                    b.Property<DateTime?>("LastHeartbeat")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("last_heartbeat");

                    b.Property<DateTime?>("RegistrationTime")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("registration_time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<bool>("SyncEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("sync_enabled");

                    b.Property<string>("SyncUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("sync_url");

                    b.HasKey("NodeId");

                    b.HasIndex("LastHeartbeat")
                        .HasDatabaseName("IX_sync_node_last_heartbeat");

                    b.ToTable("sync_node", "msosync");
                });

            modelBuilder.Entity("MSOSync.Persistence.Entities.SyncNodeGroup", b =>
                {
                    b.Property<string>("GroupId")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("group_id");

                    b.Property<string>("GroupName")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("group_name");

                    b.HasKey("GroupId");

                    b.ToTable("sync_node_group", "msosync");
                });

            modelBuilder.Entity("MSOSync.Persistence.Entities.SyncNodeSecurity", b =>
                {
                    b.Property<string>("NodeId")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("node_id");

                    b.Property<DateTime?>("CreatedTime")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("created_time");

                    b.Property<string>("NodeToken")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("node_token");

                    b.HasKey("NodeId");

                    b.ToTable("sync_node_security", "msosync");
                });

            modelBuilder.Entity("MSOSync.Persistence.Entities.SyncOutgoingBatch", b =>
                {
                    b.Property<long>("BatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("batch_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("BatchId"));

                    b.Property<DateTime?>("AckTime")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("ack_time");

                    b.Property<long>("BatchSequence")
                        .HasColumnType("bigint")
                        .HasColumnName("batch_sequence");

                    b.Property<long>("ByteCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("byte_count");

                    b.Property<string>("ChannelId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("channel_id");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("create_time");

                    b.Property<long?>("NetworkMillis")
                        .HasColumnType("bigint")
                        .HasColumnName("network_millis");

                    b.Property<DateTime?>("NextRetryTime")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("next_retry_time");

                    b.Property<string>("NodeId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("node_id");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("retry_count");

                    b.Property<int>("RowCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("row_count");

                    b.Property<DateTime?>("SentTime")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("sent_time");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint")
                        .HasColumnName("status");

                    b.HasKey("BatchId");

                    b.HasIndex("ChannelId")
                        .HasDatabaseName("IX_sync_outgoing_batch_channel");

                    b.HasIndex("NextRetryTime")
                        .HasDatabaseName("IX_sync_outgoing_batch_next_retry");

                    b.HasIndex("NodeId", "Status")
                        .HasDatabaseName("IX_sync_outgoing_batch_node_status");

                    b.ToTable("sync_outgoing_batch", "msosync");
                });

            modelBuilder.Entity("MSOSync.Persistence.Entities.SyncParameter", b =>
                {
                    b.Property<string>("ParameterName")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("parameter_name");

                    b.Property<string>("ParameterValue")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("parameter_value");

                    b.HasKey("ParameterName");

                    b.ToTable("sync_parameter", "msosync");
                });

            modelBuilder.Entity("MSOSync.Persistence.Entities.SyncParameterHist", b =>
                {
                    b.Property<long>("HistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("hist_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("HistId"));

                    b.Property<DateTime?>("ChangeTime")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("change_time");

                    b.Property<string>("ChangedBy")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("changed_by");

                    b.Property<string>("NewValue")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("new_value");

                    b.Property<string>("OldValue")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("old_value");

                    b.Property<string>("ParameterName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("parameter_name");

                    b.HasKey("HistId");

                    b.ToTable("sync_parameter_hist", "msosync");
                });

            modelBuilder.Entity("MSOSync.Persistence.Entities.SyncRegistrationRequest", b =>
                {
                    b.Property<long>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("request_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RequestId"));

                    b.Property<bool>("Approved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("approved");

                    b.Property<string>("DbType")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("db_type");

                    b.Property<string>("NodeGroup")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("node_group");

                    b.Property<string>("NodeId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("node_id");

                    b.Property<string>("NodeVersion")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("node_version");

                    b.Property<DateTime?>("RequestTime")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("request_time");

                    b.Property<string>("SyncUrl")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("sync_url");

                    b.HasKey("RequestId");

                    b.ToTable("sync_registration_request", "msosync");
                });

            modelBuilder.Entity("MSOSync.Persistence.Entities.SyncRole", b =>
                {
                    b.Property<long>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("role_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("role_name");

                    b.HasKey("RoleId");

                    b.HasIndex("RoleName")
                        .IsUnique()
                        .HasDatabaseName("UQ_sync_role_role_name");

                    b.ToTable("sync_role", "msosync");
                });

            modelBuilder.Entity("MSOSync.Persistence.Entities.SyncRouter", b =>
                {
                    b.Property<string>("RouterId")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("router_id");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("enabled");

                    b.Property<string>("RouterType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("default")
                        .HasColumnName("router_type");

                    b.Property<string>("SourceNodeGroup")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("source_node_group");

                    b.Property<string>("TargetNodeGroup")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("target_node_group");

                    b.HasKey("RouterId");

                    b.ToTable("sync_router", "msosync");
                });

            modelBuilder.Entity("MSOSync.Persistence.Entities.SyncRuntimeStats", b =>
                {
                    b.Property<long>("StatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("stat_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("StatId"));

                    b.Property<decimal?>("CpuPercent")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("cpu_percent");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("create_time");

                    b.Property<long?>("GcCount")
                        .HasColumnType("bigint")
                        .HasColumnName("gc_count");

                    b.Property<long?>("GcTimeMs")
                        .HasColumnType("bigint")
                        .HasColumnName("gc_time_ms");

                    b.Property<long?>("HeapMax")
                        .HasColumnType("bigint")
                        .HasColumnName("heap_max");

                    b.Property<long?>("HeapUsed")
                        .HasColumnType("bigint")
                        .HasColumnName("heap_used");

                    b.Property<int?>("ThreadCount")
                        .HasColumnType("int")
                        .HasColumnName("thread_count");

                    b.Property<long?>("UptimeMs")
                        .HasColumnType("bigint")
                        .HasColumnName("uptime_ms");

                    b.HasKey("StatId");

                    b.ToTable("sync_runtime_stats", "msosync");
                });

            modelBuilder.Entity("MSOSync.Persistence.Entities.SyncTrigger", b =>
                {
                    b.Property<string>("TriggerId")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("trigger_id");

                    b.Property<string>("ChannelId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("channel_id");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("enabled");

                    b.Property<DateTime?>("LastVerifiedTime")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("last_verified_time");

                    b.Property<string>("SourceTable")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("source_table");

                    b.Property<bool>("SyncOnDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("sync_on_delete");

                    b.Property<bool>("SyncOnInsert")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("sync_on_insert");

                    b.Property<bool>("SyncOnUpdate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("sync_on_update");

                    b.Property<int>("TriggerVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("trigger_version");

                    b.HasKey("TriggerId");

                    b.ToTable("sync_trigger", "msosync");
                });

            modelBuilder.Entity("MSOSync.Persistence.Entities.SyncTriggerHist", b =>
                {
                    b.Property<long>("HistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("hist_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("HistId"));

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("create_time");

                    b.Property<string>("DdlText")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ddl_text");

                    b.Property<string>("TriggerId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("trigger_id");

                    b.Property<int?>("TriggerVersion")
                        .HasColumnType("int")
                        .HasColumnName("trigger_version");

                    b.HasKey("HistId");

                    b.ToTable("sync_trigger_hist", "msosync");
                });

            modelBuilder.Entity("MSOSync.Persistence.Entities.SyncTriggerRouter", b =>
                {
                    b.Property<string>("TriggerId")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("trigger_id");

                    b.Property<string>("RouterId")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("router_id");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("enabled");

                    b.HasKey("TriggerId", "RouterId");

                    b.ToTable("sync_trigger_router", "msosync");
                });

            modelBuilder.Entity("MSOSync.Persistence.Entities.SyncUser", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UserId"));

                    b.Property<DateTime?>("CreatedTime")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("created_time");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("enabled");

                    b.Property<int>("FailedAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("failed_attempts");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("last_login");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("username");

                    b.HasKey("UserId");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("UQ_sync_user_username");

                    b.ToTable("sync_user", "msosync");
                });

            modelBuilder.Entity("MSOSync.Persistence.Entities.SyncUserRole", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId");

                    b.ToTable("sync_user_role", "msosync");
                });

            modelBuilder.Entity("MSOSync.Persistence.Entities.SyncBatchError", b =>
                {
                    b.HasOne("MSOSync.Persistence.Entities.SyncOutgoingBatch", null)
                        .WithMany()
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_sync_batch_error_batch_id");
                });
#pragma warning restore 612, 618
        }
    }
}
