// <auto-generated />
using MSOSync.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace MSOSync.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class M002_CoreTables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
