// <auto-generated />
using System;
using MSOSync.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MSOSync.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class M010_NodeSecurityHashes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MSOSync.Persistence.Entities.SyncNodeSecurity", b =>
                {
                    b.Property<string>("NodeId")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("node_id");

                    b.Property<DateTime?>("CreatedTime")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("created_time");

                    b.Property<string>("CurrentTokenHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("current_token_hash");

                    b.Property<string>("NextTokenHash")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("next_token_hash");

                    b.Property<string>("NodeToken")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("node_token");

                    b.HasKey("NodeId");

                    b.ToTable("sync_node_security", "msosync");
                });

#pragma warning restore 612, 618
        }
    }
}
