// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace MSOSync.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("M016_NodeDbConnection")]
    partial class M016_NodeDbConnection
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Intentionally minimal — EF model snapshot carries authoritative state
        }
    }
}
