// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MSOSync.Persistence;

#nullable disable

namespace MSOSync.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("M025_ParameterMetadata")]
    partial class M025_ParameterMetadata
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Intentionally minimal — EF model snapshot carries authoritative state
        }
    }
}
