// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using MSOSync.Persistence;

#nullable disable

namespace MSOSync.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("M034_BatchReplay")]
    partial class M034_BatchReplay
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // EF uses AppDbContextModelSnapshot.cs at runtime; this stub satisfies the migration runner.
        }
    }
}
